<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$countries = array(
			array('code' => 'AU', 'name' => 'Australia'),
			array('code' => 'CN', 'name' => 'China'),
			array('code' => 'JP', 'name' => 'Japan'),
			array('code' => 'TH', 'name' => 'Thailand'),
			array('code' => 'IN', 'name' => 'India'),
			array('code' => 'MY', 'name' => 'Malaysia'),
			array('code' => 'KR', 'name' => 'Kore'),
			array('code' => 'HK', 'name' => 'Hong Kong'),
			array('code' => 'TW', 'name' => 'Taiwan'),
			array('code' => 'PH', 'name' => 'Philippines'),
			array('code' => 'VN', 'name' => 'Vietnam'),
			array('code' => 'FR', 'name' => 'France'),
			array('code' => 'EU', 'name' => 'Europe'),
			array('code' => 'DE', 'name' => 'Germany'),
			array('code' => 'SE', 'name' => 'Sweden'),
			array('code' => 'IT', 'name' => 'Italy'),
			array('code' => 'GR', 'name' => 'Greece'),
			array('code' => 'ES', 'name' => 'Spain'),
			array('code' => 'AT', 'name' => 'Austria'),
			array('code' => 'GB', 'name' => 'United Kingdom'),
			array('code' => 'NL', 'name' => 'Netherlands'),
			array('code' => 'BE', 'name' => 'Belgium'),
			array('code' => 'CH', 'name' => 'Switzerland'),
			array('code' => 'AE', 'name' => 'United Arab Emirates'),
			array('code' => 'IL', 'name' => 'Israel'),
			array('code' => 'UA', 'name' => 'Ukraine'),
			array('code' => 'RU', 'name' => 'Russian Federation'),
			array('code' => 'KZ', 'name' => 'Kazakhstan'),
			array('code' => 'PT', 'name' => 'Portugal'),
			array('code' => 'SA', 'name' => 'Saudi Arabia'),
			array('code' => 'DK', 'name' => 'Denmark'),
			array('code' => 'IR', 'name' => 'Ira'),
			array('code' => 'NO', 'name' => 'Norway'),
			array('code' => 'US', 'name' => 'United States'),
			array('code' => 'MX', 'name' => 'Mexico'),
			array('code' => 'CA', 'name' => 'Canada'),
			array('code' => 'A1', 'name' => 'Anonymous Proxy'),
			array('code' => 'SY', 'name' => 'Syrian Arab Republic'),
			array('code' => 'CY', 'name' => 'Cyprus'),
			array('code' => 'CZ', 'name' => 'Czech Republic'),
			array('code' => 'IQ', 'name' => 'Iraq'),
			array('code' => 'TR', 'name' => 'Turkey'),
			array('code' => 'RO', 'name' => 'Romania'),
			array('code' => 'LB', 'name' => 'Lebanon'),
			array('code' => 'HU', 'name' => 'Hungary'),
			array('code' => 'GE', 'name' => 'Georgia'),
			array('code' => 'BR', 'name' => 'Brazil'),
			array('code' => 'AZ', 'name' => 'Azerbaijan'),
			array('code' => 'A2', 'name' => 'Satellite Provider'),
			array('code' => 'PS', 'name' => 'Palestinian Territory'),
			array('code' => 'LT', 'name' => 'Lithuania'),
			array('code' => 'OM', 'name' => 'Oman'),
			array('code' => 'SK', 'name' => 'Slovakia'),
			array('code' => 'RS', 'name' => 'Serbia'),
			array('code' => 'FI', 'name' => 'Finland'),
			array('code' => 'IS', 'name' => 'Iceland'),
			array('code' => 'BG', 'name' => 'Bulgaria'),
			array('code' => 'SI', 'name' => 'Slovenia'),
			array('code' => 'MD', 'name' => 'Moldov'),
			array('code' => 'MK', 'name' => 'Macedonia'),
			array('code' => 'LI', 'name' => 'Liechtenstein'),
			array('code' => 'JE', 'name' => 'Jersey'),
			array('code' => 'PL', 'name' => 'Poland'),
			array('code' => 'HR', 'name' => 'Croatia'),
			array('code' => 'BA', 'name' => 'Bosnia and Herzegovina'),
			array('code' => 'EE', 'name' => 'Estonia'),
			array('code' => 'LV', 'name' => 'Latvia'),
			array('code' => 'JO', 'name' => 'Jordan'),
			array('code' => 'KG', 'name' => 'Kyrgyzstan'),
			array('code' => 'RE', 'name' => 'Reunion'),
			array('code' => 'IE', 'name' => 'Ireland'),
			array('code' => 'LY', 'name' => 'Libya'),
			array('code' => 'LU', 'name' => 'Luxembourg'),
			array('code' => 'AM', 'name' => 'Armenia'),
			array('code' => 'VG', 'name' => 'Virgin Island'),
			array('code' => 'YE', 'name' => 'Yemen'),
			array('code' => 'BY', 'name' => 'Belarus'),
			array('code' => 'GI', 'name' => 'Gibraltar'),
			array('code' => 'MQ', 'name' => 'Martinique'),
			array('code' => 'PA', 'name' => 'Panama'),
			array('code' => 'DO', 'name' => 'Dominican Republic'),
			array('code' => 'GU', 'name' => 'Guam'),
			array('code' => 'PR', 'name' => 'Puerto Rico'),
			array('code' => 'VI', 'name' => 'Virgin Island'),
			array('code' => 'MN', 'name' => 'Mongolia'),
			array('code' => 'NZ', 'name' => 'New Zealand'),
			array('code' => 'SG', 'name' => 'Singapore'),
			array('code' => 'ID', 'name' => 'Indonesia'),
			array('code' => 'NP', 'name' => 'Nepal'),
			array('code' => 'PG', 'name' => 'Papua New Guinea'),
			array('code' => 'PK', 'name' => 'Pakistan'),
			array('code' => 'AP', 'name' => 'Asia/Pacific Region'),
			array('code' => 'BS', 'name' => 'Bahamas'),
			array('code' => 'LC', 'name' => 'Saint Lucia'),
			array('code' => 'AR', 'name' => 'Argentina'),
			array('code' => 'BD', 'name' => 'Bangladesh'),
			array('code' => 'TK', 'name' => 'Tokelau'),
			array('code' => 'KH', 'name' => 'Cambodia'),
			array('code' => 'MO', 'name' => 'Macau'),
			array('code' => 'MV', 'name' => 'Maldives'),
			array('code' => 'AF', 'name' => 'Afghanistan'),
			array('code' => 'NC', 'name' => 'New Caledonia'),
			array('code' => 'FJ', 'name' => 'Fiji'),
			array('code' => 'WF', 'name' => 'Wallis and Futuna'),
			array('code' => 'QA', 'name' => 'Qatar'),
			array('code' => 'AL', 'name' => 'Albania'),
			array('code' => 'BZ', 'name' => 'Belize'),
			array('code' => 'UZ', 'name' => 'Uzbekistan'),
			array('code' => 'KW', 'name' => 'Kuwait'),
			array('code' => 'ME', 'name' => 'Montenegro'),
			array('code' => 'PE', 'name' => 'Peru'),
			array('code' => 'BM', 'name' => 'Bermuda'),
			array('code' => 'CW', 'name' => 'Curacao'),
			array('code' => 'CO', 'name' => 'Colombia'),
			array('code' => 'VE', 'name' => 'Venezuela'),
			array('code' => 'CL', 'name' => 'Chile'),
			array('code' => 'EC', 'name' => 'Ecuador'),
			array('code' => 'ZA', 'name' => 'South Africa'),
			array('code' => 'IM', 'name' => 'Isle of Man'),
			array('code' => 'BO', 'name' => 'Bolivia'),
			array('code' => 'GG', 'name' => 'Guernsey'),
			array('code' => 'MT', 'name' => 'Malta'),
			array('code' => 'TJ', 'name' => 'Tajikistan'),
			array('code' => 'SC', 'name' => 'Seychelles'),
			array('code' => 'BH', 'name' => 'Bahrain'),
			array('code' => 'EG', 'name' => 'Egypt'),
			array('code' => 'ZW', 'name' => 'Zimbabwe'),
			array('code' => 'LR', 'name' => 'Liberia'),
			array('code' => 'KE', 'name' => 'Kenya'),
			array('code' => 'GH', 'name' => 'Ghana'),
			array('code' => 'NG', 'name' => 'Nigeria'),
			array('code' => 'TZ', 'name' => 'Tanzani'),
			array('code' => 'ZM', 'name' => 'Zambia'),
			array('code' => 'MG', 'name' => 'Madagascar'),
			array('code' => 'AO', 'name' => 'Angola'),
			array('code' => 'NA', 'name' => 'Namibia'),
			array('code' => 'CI', 'name' => 'Cote D\'Ivoire'),
			array('code' => 'SD', 'name' => 'Sudan'),
			array('code' => 'CM', 'name' => 'Cameroon'),
			array('code' => 'MW', 'name' => 'Malawi'),
			array('code' => 'GA', 'name' => 'Gabon'),
			array('code' => 'ML', 'name' => 'Mali'),
			array('code' => 'BJ', 'name' => 'Benin'),
			array('code' => 'TD', 'name' => 'Chad'),
			array('code' => 'BW', 'name' => 'Botswana'),
			array('code' => 'CV', 'name' => 'Cape Verde'),
			array('code' => 'RW', 'name' => 'Rwanda'),
			array('code' => 'CG', 'name' => 'Congo'),
			array('code' => 'UG', 'name' => 'Uganda'),
			array('code' => 'MZ', 'name' => 'Mozambique'),
			array('code' => 'GM', 'name' => 'Gambia'),
			array('code' => 'LS', 'name' => 'Lesotho'),
			array('code' => 'MU', 'name' => 'Mauritius'),
			array('code' => 'MA', 'name' => 'Morocco'),
			array('code' => 'DZ', 'name' => 'Algeria'),
			array('code' => 'GN', 'name' => 'Guinea'),
			array('code' => 'CD', 'name' => 'Cong'),
			array('code' => 'SZ', 'name' => 'Swaziland'),
			array('code' => 'BF', 'name' => 'Burkina Faso'),
			array('code' => 'SL', 'name' => 'Sierra Leone'),
			array('code' => 'SO', 'name' => 'Somalia'),
			array('code' => 'NE', 'name' => 'Niger'),
			array('code' => 'CF', 'name' => 'Central African Republic'),
			array('code' => 'TG', 'name' => 'Togo'),
			array('code' => 'BI', 'name' => 'Burundi'),
			array('code' => 'GQ', 'name' => 'Equatorial Guinea'),
			array('code' => 'SS', 'name' => 'South Sudan'),
			array('code' => 'SN', 'name' => 'Senegal'),
			array('code' => 'MR', 'name' => 'Mauritania'),
			array('code' => 'DJ', 'name' => 'Djibouti'),
			array('code' => 'KM', 'name' => 'Comoros'),
			array('code' => 'IO', 'name' => 'British Indian Ocean Territory'),
			array('code' => 'TN', 'name' => 'Tunisia'),
			array('code' => 'GL', 'name' => 'Greenland'),
			array('code' => 'VA', 'name' => 'Holy See (Vatican City State)'),
			array('code' => 'CR', 'name' => 'Costa Rica'),
			array('code' => 'KY', 'name' => 'Cayman Islands'),
			array('code' => 'JM', 'name' => 'Jamaica'),
			array('code' => 'GT', 'name' => 'Guatemala'),
			array('code' => 'MH', 'name' => 'Marshall Islands'),
			array('code' => 'AQ', 'name' => 'Antarctica'),
			array('code' => 'BB', 'name' => 'Barbados'),
			array('code' => 'AW', 'name' => 'Aruba'),
			array('code' => 'MC', 'name' => 'Monaco'),
			array('code' => 'AI', 'name' => 'Anguilla'),
			array('code' => 'KN', 'name' => 'Saint Kitts and Nevis'),
			array('code' => 'GD', 'name' => 'Grenada'),
			array('code' => 'PY', 'name' => 'Paraguay'),
			array('code' => 'MS', 'name' => 'Montserrat'),
			array('code' => 'TC', 'name' => 'Turks and Caicos Islands'),
			array('code' => 'AG', 'name' => 'Antigua and Barbuda'),
			array('code' => 'TV', 'name' => 'Tuvalu'),
			array('code' => 'PF', 'name' => 'French Polynesia'),
			array('code' => 'SB', 'name' => 'Solomon Islands'),
			array('code' => 'VU', 'name' => 'Vanuatu'),
			array('code' => 'ER', 'name' => 'Eritrea'),
			array('code' => 'TT', 'name' => 'Trinidad and Tobago'),
			array('code' => 'AD', 'name' => 'Andorra'),
			array('code' => 'HT', 'name' => 'Haiti'),
			array('code' => 'SH', 'name' => 'Saint Helena'),
			array('code' => 'FM', 'name' => 'Micronesi'),
			array('code' => 'SV', 'name' => 'El Salvador'),
			array('code' => 'HN', 'name' => 'Honduras'),
			array('code' => 'UY', 'name' => 'Uruguay'),
			array('code' => 'LK', 'name' => 'Sri Lanka'),
			array('code' => 'EH', 'name' => 'Western Sahara'),
			array('code' => 'CX', 'name' => 'Christmas Island'),
			array('code' => 'WS', 'name' => 'Samoa'),
			array('code' => 'SR', 'name' => 'Suriname'),
			array('code' => 'CK', 'name' => 'Cook Islands'),
			array('code' => 'KI', 'name' => 'Kiribati'),
			array('code' => 'NU', 'name' => 'Niue'),
			array('code' => 'TO', 'name' => 'Tonga'),
			array('code' => 'TF', 'name' => 'French Southern Territories'),
			array('code' => 'YT', 'name' => 'Mayotte'),
			array('code' => 'NF', 'name' => 'Norfolk Island'),
			array('code' => 'BN', 'name' => 'Brunei Darussalam'),
			array('code' => 'TM', 'name' => 'Turkmenistan'),
			array('code' => 'PN', 'name' => 'Pitcairn Islands'),
			array('code' => 'SM', 'name' => 'San Marino'),
			array('code' => 'AX', 'name' => 'Aland Islands'),
			array('code' => 'FO', 'name' => 'Faroe Islands'),
			array('code' => 'SJ', 'name' => 'Svalbard and Jan Mayen'),
			array('code' => 'CC', 'name' => 'Cocos (Keeling) Islands'),
			array('code' => 'NR', 'name' => 'Nauru'),
			array('code' => 'GS', 'name' => 'South Georgia and the South Sandwich Islands'),
			array('code' => 'UM', 'name' => 'United States Minor Outlying Islands'),
			array('code' => 'GW', 'name' => 'Guinea-Bissau'),
			array('code' => 'PW', 'name' => 'Palau'),
			array('code' => 'AS', 'name' => 'American Samoa'),
			array('code' => 'BT', 'name' => 'Bhutan'),
			array('code' => 'GF', 'name' => 'French Guiana'),
			array('code' => 'GP', 'name' => 'Guadeloupe'),
			array('code' => 'MF', 'name' => 'Saint Martin'),
			array('code' => 'VC', 'name' => 'Saint Vincent and the Grenadines'),
			array('code' => 'PM', 'name' => 'Saint Pierre and Miquelon'),
			array('code' => 'BL', 'name' => 'Saint Barthelemy'),
			array('code' => 'DM', 'name' => 'Dominica'),
			array('code' => 'ST', 'name' => 'Sao Tome and Principe'),
			array('code' => 'KP', 'name' => 'Kore'),
			array('code' => 'FK', 'name' => 'Falkland Islands (Malvinas)'),
			array('code' => 'MP', 'name' => 'Northern Mariana Islands'),
			array('code' => 'TL', 'name' => 'Timor-Leste'),
			array('code' => 'BQ', 'name' => 'Bonair'),
			array('code' => 'MM', 'name' => 'Myanmar'),
			array('code' => 'NI', 'name' => 'Nicaragua'),
			array('code' => 'SX', 'name' => 'Sint Maarten (Dutch part)'),
			array('code' => 'GY', 'name' => 'Guyana'),
			array('code' => 'LA', 'name' => 'Lao People\'s Democratic Republic'),
			array('code' => 'CU', 'name' => 'Cuba'),
			array('code' => 'ET', 'name' => 'Ethiopia')
		);

		Country::query()->insert($countries);
	}
}
