POST /user/password-reset HTTP/1.1
Content-Type: application/json
Host: {{ host }}
Accept-Language: es

{
  "email": "adrian@localhost.com",
  "password": "password2",
  "password_confirmation": "password2",
  "token": "431316"
}