POST /user/register HTTP/1.1
Content-Type: application/json
Host: {{ host }}
Accept-Language: es

{
  "first_name": "Adrian",
  "last_name": "Capote",
  "email": "email@email.email",
  "password": "password",
  "password_confirmation": "password"
}