POST /shop/pack HTTP/1.1
Content-Type: application/json
Host: {{ host }}
Accept-Language: es
Authorization: {{ token }}

{
  "delivery_method": "delivery_method",
  "destinataries":[
    {
      "first_name": "first_name",
      "last_name": "last_name",
      "address": "address"
    }
  ],
  "products":[
    {
      "id":1,
      "cart_cant":5,
      "options_details":{
        "color":"red"
      }
    },
    {
      "id":2,
      "cart_cant":5,
      "options_details":{
        "color":"red"
      }
    },
    {
      "id":3,
      "cart_cant":5,
      "options_details":{
        "color":"red"
      }
    }
  ]
}