POST /vendor/product HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Host: {{ host }}
Accept-Language: es
Authorization: {{ token }}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

title

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="brand"

brand

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

<h1>Description</h1>

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

28

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="weight"

28

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="tags[0]"

tag0

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="tags[1]"

tag1

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="options[colors][0]"

colorRed

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="options[colors][1]"

colorBlue

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="vendor_id"

1

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="type_id"

1

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="cant"

5

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images[0]"; filename="img2.png"
Content-Type: image/png

< ./img.png


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images[1]"; filename="img.png"
Content-Type: image/png

< ./img.png

------WebKitFormBoundary7MA4YWxkTrZu0gW--